//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package io.github.luiseduardobrito.social;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class AppPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public AppPrefs_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_AppPrefs"), 0));
        this.context_ = context;
    }

    public AppPrefs_.AppPrefsEditor_ edit() {
        return new AppPrefs_.AppPrefsEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public StringPrefField userEmail() {
        return stringField("userEmail", "");
    }

    public StringPrefField userId() {
        return stringField("userId", "");
    }

    public StringPrefField userName() {
        return stringField("userName", "");
    }

    public final static class AppPrefsEditor_
        extends EditorHelper<AppPrefs_.AppPrefsEditor_>
    {


        AppPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<AppPrefs_.AppPrefsEditor_> userEmail() {
            return stringField("userEmail");
        }

        public StringPrefEditorField<AppPrefs_.AppPrefsEditor_> userId() {
            return stringField("userId");
        }

        public StringPrefEditorField<AppPrefs_.AppPrefsEditor_> userName() {
            return stringField("userName");
        }

    }

}
