//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package io.github.luiseduardobrito.social.util;

import android.content.Context;
import android.net.ConnectivityManager;

public final class AppNetworkUtil_
    extends AppNetworkUtil
{

    private Context context_;

    private AppNetworkUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static AppNetworkUtil_ getInstance_(Context context) {
        return new AppNetworkUtil_(context);
    }

    private void init_() {
        cm = ((ConnectivityManager) context_.getSystemService(Context.CONNECTIVITY_SERVICE));
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
