//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package io.github.luiseduardobrito.social.push;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AppPushManager_
    extends AppPushManager
{

    private Context context_;
    private static AppPushManager_ instance_;

    private AppPushManager_(Context context) {
        context_ = context;
    }

    public static AppPushManager_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new AppPushManager_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
