//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package io.github.luiseduardobrito.social.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Spinner;
import android.widget.VideoView;
import io.github.luiseduardobrito.social.R.id;
import io.github.luiseduardobrito.social.R.layout;
import io.github.luiseduardobrito.social.model.MessageListManager_;
import io.github.luiseduardobrito.social.model.MessageType;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CreatorActivity_
    extends CreatorActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_creator);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mMessageList = MessageListManager_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CreatorActivity_.IntentBuilder_ intent(Context context) {
        return new CreatorActivity_.IntentBuilder_(context);
    }

    public static CreatorActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CreatorActivity_.IntentBuilder_(fragment);
    }

    public static CreatorActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CreatorActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mTitleEdit = ((EditText) hasViews.findViewById(id.title_edit));
        mPointsEdit = ((EditText) hasViews.findViewById(id.points_edit));
        mVideoView = ((VideoView) hasViews.findViewById(id.videoView));
        typeSpinner = ((Spinner) hasViews.findViewById(id.type_edit));
        mImageView = ((ImageView) hasViews.findViewById(id.imageView));
        {
            View view = hasViews.findViewById(id.submit_message);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CreatorActivity_.this.submitMessage();
                    }

                }
                );
            }
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(io.github.luiseduardobrito.social.R.menu.creator, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == id.action_gallery) {
            actionGallery();
            return true;
        }
        if (itemId_ == id.action_capture) {
            actionCapture();
            return true;
        }
        if (itemId_ == id.action_video) {
            actionVideo();
            return true;
        }
        return false;
    }

    @Override
    public void dimissDialog() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                CreatorActivity_.super.dimissDialog();
            }

        }
        );
    }

    @Override
    public void notifyErrorResult(final String message) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                CreatorActivity_.super.notifyErrorResult(message);
            }

        }
        );
    }

    @Override
    public void createAndSaveInBackground(final String title, final MessageType type, final Integer points) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    CreatorActivity_.super.createAndSaveInBackground(title, type, points);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, CreatorActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CreatorActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CreatorActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public CreatorActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
