//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package io.github.luiseduardobrito.social.model;

import android.content.Context;
import io.github.luiseduardobrito.social.util.AppNetworkUtil_;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MessageListManager_
    extends MessageListManager
{

    private Context context_;
    private static MessageListManager_ instance_;

    private MessageListManager_(Context context) {
        context_ = context;
    }

    public static MessageListManager_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new MessageListManager_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        network = AppNetworkUtil_.getInstance_(context_);
        init();
    }

}
